#Design an automation script that displays information about all running processes:
# Process Name
# PID
# Username

import time
import os
import sys
import psutil
import schedule
import smtplib
from email.message import EmailMessage

def send_mail(sender, app_password,receiver,subject,body,LogFileName):
    
    msg = EmailMessage()
    
    msg ["From"] = sender
    msg ["To"] = receiver
    msg ["Subject"] = subject
    
    msg.set_content(body)
    
    with open(LogFileName, "rb") as fobj:

        FileData = fobj.read()

        msg.add_attachment(FileData, maintype="application",subtype="octet-stream",filename=os.path.basename(LogFileName))

    smtp = smtplib.SMTP_SSL("smtp.gmail.com",465)
    
    smtp.login(sender,app_password)
    
    smtp.send_message(msg)
    
    smtp.quit()

def ProcessScan():
    ListProcess = []
    
    for proc in psutil.process_iter():
        info = proc.as_dict(attrs=["pid","name","username"])
        
        ListProcess.append(info)
        
    return ListProcess
        
def CreateLog(FolderName,ReceiverEmail):
    
    Border = "_"*70
    
    Ret = False
    
    Ret = os.path.exists(FolderName)
    if(Ret == True):
        Ret = os.path.isdir(FolderName)
        if(Ret == False):
            print("unable to directory execute there is no directory ")
            
    else:
        os.mkdir(FolderName)
        print("Directory is created succesfully")
   
    timestamp = time.strftime("%Y_%m_%d-%H_%M_%S")
    
    FileName = ("Marvellous_%s.log" %timestamp)
    
    print(f"File is created with name {FileName}")
    
    FilePath = os.path.join(FolderName, FileName)
    
    fobj = open(FilePath , "w")
    
    fobj.write(Border + "\n\n")
    
    fobj.write("Information Of Running Processes\n")    
    
    fobj.write(Border + "\n\n")
    
    # Process info
    Data = ProcessScan()
    
    for info in Data:
        
        fobj.write("PID : %s\n" %info.get("pid"))
        fobj.write("Name : %s\n" %info.get("name"))
        fobj.write("Username : %s\n" %info.get("username"))
        fobj.write(Border + "\n")
        
    fobj.write(Border + "\n")
    fobj.write("----------------End of Log File---------------\n")
    fobj.write(Border + "\n")
    
    fobj.close()
    
    sender_email = "mahek967386@gmail.com"
    app_password = "nbbn gttr cfkx hvav"
    
    subject = "Automated System Surveillance Log Report"
    body = """Please find the attached log file containing information about all currently running processes, including Process Name, PID, and Username.

This log file was automatically generated by the Python Automation System.
    Regards 
    Mahek Pathan
    """
        
    send_mail(sender_email,app_password,ReceiverEmail,subject,body,FilePath)
    print("Marvellous mail sent successfully")
    
def main():
    
    Border = "_"*70
    
    ProcessScan()
    
    if(len(sys.argv )== 2):
        if(sys.argv[1] == "--H" or sys.argv[1] == "--h"):
            print("This automation script is used to information of running processes")
            print("For better usage plz check --u flag")
            
        elif(sys.argv[1] == "--u" or sys.argv[1] == "--U"):
            print("please execute the script as ")
            print("python FileName.py DirectoryName")
            
        else:
            print("Unable to processing as there is no matching argument")
            print("Please use --h or --u flag for getting more details")
                     
    elif(len(sys.argv) == 3):
        
        FolderName = sys.argv[1]
        ReceiverEmail = sys.argv[2]

        schedule.every(5).seconds.do(CreateLog,FolderName,ReceiverEmail)
        
        while True:
            schedule.run_pending()
            time.sleep(1)
        
    else:
        print("Invalid number of arguments")
        print("Unable to Process as arguments are not matching")
        print("Please use --h or --u flag for getting more details")
        
if __name__ == "__main__":
    main()